name: python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  black:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: black --check pycreep examples test
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: pylint pycreep
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: pytest test